### ISSUE TITLE
navbar, footer 퍼블리싱

### ISSUE THREAD

**Issue by alswlfl29** [Sejin-999/webPro-TeamPle#1]
<img width="1454" alt="스크린샷 2022-11-25 오후 11 29 49" src="https://user-images.githubusercontent.com/79428205/204006942-e88aa4aa-40fd-4773-9c89-10973f0cb665.png">

공통 부분이라 각각 jsp 만들어 놓아서 가져다가 사용하시면 됩니다.
가운데 부분에 각자 맡으신거 추가하시면 될거 같아요!

**Comment by teawon** [comment]
고생하셨습니다!

저는 구현해주신 틀 기반으로 로그인 , 회원가입 페이지 및 세션 여부에 따라 Navbar에 나타나는 값을 바꾸도록 기능구현 이어서 진행하겠습니다.
