### ISSUE TITLE
칵테일 상세페이지

### ISSUE THREAD

**Issue by Sejin-999** [Sejin-999/webPro-TeamPle#14]
![1](https://user-images.githubusercontent.com/76008226/207999271-12622aaf-2fbf-4409-9e98-f6a21b93e285.PNG)
![2](https://user-images.githubusercontent.com/76008226/207999281-6a6975f5-38ff-43bb-850c-0608d92e955d.PNG)

위 화면 처럼 칵테일이름과 베이스, 재료에 대해 나올수 있도록했습니다. 사진 백그라운드가 하얀색이여서 우선 배경색은 하얀색으로 했습니다. 간단한 css 스타일링과 호버부분만 만들었습니다. 

![3](https://user-images.githubusercontent.com/76008226/207999381-a869b9e0-9e55-45a8-b421-c0bca2f85343.PNG)

DrinkDetail  패키지 파일이 현재 작동중인 페이지에 적용되어있습니다. 

컨트롤러 부분을 먼저 작업하신 부분에 추가하고 만들어 혹 겹쳐 충돌 , 작업하시고 안올리신게 삭제될까봐 detail 브런치에 파일 전체를 따로 올려놨습니다. 
![4](https://user-images.githubusercontent.com/76008226/207999587-e62b006d-1abe-4060-856d-403e7307b8c6.PNG)

url 부분만 완성하면 되는데 여기서 문제가 있어 작업 중에 있습니다. 혹시 도움을 주 실수 있으면 감사하겠습니다.
현재는 drink_id 를 1로  고정된 값으로 넘겨줍니다.

![5](https://user-images.githubusercontent.com/76008226/207999707-b23a1cd7-790d-496b-a8ab-c8ff809b515d.PNG)

+ 칵테일에 대한 내용 : 예를 들어  진토닉 : 
칵테일의 한 종류. 말라리아 때문에 탄생하게 되었는데 퀴닌은 그냥 먹기에는 쓴맛 때문에 먹이게 하려고 술, 설탕 등을 넣어서 마신게 기원이다.
이런식으로 칵테일 컨텐츠를 넣어서 이미지를 호버하면 나올 수 있도록 만들어는 뒀는데 한번 고려해주시면 감사하겠습니다.

예상보다 늦어져 죄송합니다.

**Comment by teawon** [comment]
고생하셨습니다!

우선 url링크같은 경우는
```
<c:when test="${baseList != null && fn:length(baseList)>0}">
							<c:forEach var="base" items="${baseList}" varStatus="status">
								<c:if test="{i%j==0}">
									<tr style="padding-right: 5%; padding-left: 5%; padding-top:3%;">
								</c:if>
								<td  
									style="vertical-alight: top; padding-right: 2.5%; padding-left: 2.5%;">
									<a class="a"
									href="drinkController?action=getSearchList&base_id=${base.base_id}">
										<figure class="image">
											<img class="imageSize" src="${base.image}" >
											<figcaption
												style="text-align: center; color: #FFFFFF; text-decoration: none; font-size: 2rem;">${base.name}</figcaption>
										</figure>
								</a>
								</td>
								<c:if test="${i%j == j-1}">
									</tr>
								</c:if>
								<c:set var="i" value="${i+1}" />
							</c:forEach>
						</c:when>
```
main.jsp코드중 일부인데 보시면 리스트데이터를 for문으로 요소를 출력하고있습니다.
여기서 
```
<a class="a" href="drinkController?action=getSearchList&base_id=${base.base_id}">
```
위 부분과 같이 넘겨주려는 자신의 ID값을 변수로 넣어서 표현하시면 해당 칵테일에 대한 id값을 넘길 수 있습니다. 자세한건 코드 참고하시면 좋을 것 같아요

- 호버시 술에 대한 정보를 나타내는 아이디어는 정말 좋은 것 같습니다. 완성도가 훨씬 올라갈 것 같다고 생각했는데요 
그러려면 일단 DB에 설명을 나타내는 필드값을 추가하고 등록할때도 설명문구를 추가하도록 수정을 해야할것 같아요
다만 DB테이블을 수정하면 각자 작업하던 테이블에 수정을 해야해서 나머지 기능이 다 완성되면 향후에 추가하는 방향으로 진행하는것이 좋을 것 같습니다

- 깃허브에서 브랜치 자체를 분리했을때 이점이 main브랜치에 합치기전에는 뭘 해도 상관이없기때문에 충돌이 걱정된다하셔도 PR요청때 꼼꼼히 보면 되서 기존의 main브랜치 내용을 rebase하셔서 (혹은 그냥 main브랜치 내용 받아와서) 브랜치에서 따로 작업하시는게 더 좋을 것 같아요 지금 나머지 기능은 그대로 구현이 되어있어서 작업 다 마치고 옮기시는 것보다 아에 한번에 이어서 작업하시는게 전체적인 테스트 +  작업부분에서  편하실 것 같습니다.

**Comment by Sejin-999** [comment]
넵 확인했습니다.
